"""user role collumn added

Revision ID: 15c1f79317f9
Revises: 73bff620700c
Create Date: 2026-09-24 13:33:51.980594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c1f79317f9'
down_revision: Union[str, Sequence[str], None] = '73bff620700c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'CANDIDATE', name='user_role'), server_default='CANDIDATE', nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'role')
    # ### end Alembic commands ###
    
def upgrade() -> None:
    user_role = sa.Enum(
        'ADMIN',
        'RECRUITER',
        'CANDIDATE',
        name='user_role'
    )

    user_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            user_role,
            server_default='CANDIDATE',
            nullable=True
        )
    )


def downgrade() -> None:
    op.drop_column('users', 'role')

    user_role = sa.Enum(
        'ADMIN',
        'RECRUITER',
        'CANDIDATE',
        name='user_role'
    )

    user_role.drop(op.get_bind(), checkfirst=True)
